version = 1

[install]
go.pkg-path = "go"
go.version = "^1.25.2"

claude-code.pkg-path = "claude-code"
claude-code.version = "^2.0.37"

golangci-lint.pkg-path = "golangci-lint"
golangci-lint.version = "^2.6.0"

goreleaser.pkg-path = "goreleaser"
goreleaser.version = "^2.12.7"

go-task.pkg-path = "go-task"
go-task.version = "^3.45.4"

prettier.pkg-path = "prettier"
prettier.version = "^3.6.2"

[hook]
on-activate = """
  export GOENV="$FLOX_ENV_CACHE/goenv"
  go get .

  source <(goreleaser completion zsh)
  source <(task --completion zsh)
"""
